#!/bin/bash
module load python3

for i in {18..22}
do
#mkdir dir_$i
cd dir_$i
#cp ../../MD_equil/dir_$i/$i.seq .
#cp ../../MD_equil/dir_$i/BAL.opls .
#cp ../../MD_equil/dir_$i/final.crd .
#cp ../pmf.exe .
#cp ../*.py .
#cp ../../$i.seq .
echo $i > num
python calculator.py final.crd >> num
./pmf.exe < num > log.$i &
cd ..
done
wait
